calendar = "Календар"

language = "Мова"

paper_size = "Розмір паперу"
paper_size_a4 = "A4 (210 × 297 мм)"

month = "Місяць"
month_year = "Місяць і рік"
month_all = "Все"
month_january = "Січень"
month_february = "Лютий"
month_march = "Березень"
month_april = "Квітень"
month_may = "Травень"
month_june = "Червень"
month_july = "Липень"
month_august = "Серпень"
month_september = "Вересень"
month_october = "Жовтень"
month_november = "Листопад"
month_december = "Грудень"

first_day_of_week = "Перший день тижня"
first_day_of_week_sunday = "Неділя"
first_day_of_week_monday = "Понеділок"

days = "Дні"
loading = "Завантаження..."
font_family = "Шрифт"
font_size = "Розмір шрифта"
color = "Колір"
weekend_color = "Вихідні"
inactive_color = "Неактивні"
format = "Формат"

x = "X, мм"
y = "Y, мм"
x_step = "Крок за X, мм"
y_step = "Крок за Y, мм"

show_invactive_days = "Показати дні поза поточним місяцем"

weekdays = "Дні тижня"
weekday_short_sunday = "Нд"
weekday_short_monday = "Пн"
weekday_short_tuesday = "Вт"
weekday_short_wednesday = "Ср"
weekday_short_thursday = "Чт"
weekday_short_friday = "Пт"
weekday_short_saturday = "Сб"

weekday_shortest_sunday = "Н"
weekday_shortest_monday = "П"
weekday_shortest_tuesday = "В"
weekday_shortest_wednesday = "С"
weekday_shortest_thursday = "Ч"
weekday_shortest_friday = "П"
weekday_shortest_saturday = "С"

week_numbers = "Номери тижнів"

show = " "
hide = " "
show_preview = "Показати"
hide_preview = "Приховати"
download = "Завантажити"

made_by = "Зроблено"
konstantin_chukhlomin = "Костянтином Чухломіним"
