name: main

on:
  push:
    branches:
      - main

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Remove fonts
        run: rm -rf pages/fonts

      - name: Deploy
        uses: cloudflare/wrangler-action@v3.8.0
        if: github.event_name == 'push' && !contains(github.event.head_commit.message, '[skip deploy]')
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          command: pages deploy pages --project-name=calendar --branch=main --commit-dirty=true
